#709: Lighthouse check: Cookiebanner ARIA
grrr-amsterdam/cookie-consent pull request #40
Opened 2024-07-29 15:54 UTC by CountNick

Fixes the aria issues that were detected with lighthouse

2024-07-30 13:09 UTC, MicheleNL requested changes
Ha, fijn dat je hiermee bezig bent geweest. Ik heb nog wel wat vragen / opmerkingen, zoals je ziet in de comments.
Je begeleidend schrijven bij de PR was wel wat summier. Dus heb zelf een Lighthouse check uitgevoerd bij een willekeurig project (Melkweg) om te zien welke issues je nu weg aan het werken bent.

Ik denk dat nog niet alles klopt. Is er een manier waarop jij dit in de browser test? 

Lighthouse kan soms wat lastig te interpreteren zijn. Lighthouse maakt gebruik van de "axe-core". Er is ook een eigen Axe Devtools, die ik wel eens gebruik. Die geeft soms net wat meer uitleg. ([Chrome extension](https://chromewebstore.google.com/detail/axe-devtools-web-accessib/lhdoppojpmngadmnindnejefpokejbdd))

Daarnaast geeft Lighthouse ook nog wat "best practices". Het lijkt me goed om die ook mee te nemen. In dit geval gaat het vooral om een CSS aanpassing, dus die is relatief eenvoudig. 

Best practices zijn in dit geval non-normatief, wat zoveel betekent als dat ze niet verplicht zijn volgens de guidelines. Maar wel goed om even mee te pakken indien mogelijk. 
<img width="745" alt="Screenshot 2024-07-30 at 15 09 08" src="https://github.com/user-attachments/assets/48206a39-5045-4671-a9a1-e29eb3561209">

2024-07-31 11:44 UTC, CountNick commented on src/cookie-consent.mjs
> +    <aside part="${this.config.prefix}" id="${this.config.prefix}" class="${this.config.prefix} js-cookie-bar" aria-role="dialog" aria-live="polite" aria-labelledby="${this.config.prefix}__title" ari
Ah ja dit moest inderdaad `role="dialog"` blijven, ik blijf hier alleen wel deze melding voor krijgen met `role="dialog"` vandaar dat ik het een en ander aan het proberen was
<img width="693" alt="Screenshot 2024-07-31 at 13 44 03" src="https://github.com/user-attachments/assets/a253a9a3-5f72-4fee-8244-a39b550c06fe">

2024-07-31 11:48 UTC, CountNick commented on src/dialog-tablist.mjs
> +      <li part="${PREFIX}__tab-list-item" role="tab">
Ja, deze is eigenlijk echt allen toegevoegd zodat er geen aria warning verschijnt uit de lighthouse check. Als `role="tablist"` geen children heeft met `role="tab"` krijg je namelijk warning
<img width="696" alt="Screenshot 2024-07-31 at 13 48 25" src="https://github.com/user-attachments/assets/e526e937-c5a0-479e-ac77-4cbe9c544ad9">

2024-07-31 11:53 UTC, CountNick commented on src/dialog-tablist.mjs
> +            aria-owns="${PREFIX}__tab-list"
Lighthouse gaf aan dat `role="tablist"` children nodig heeft met een bepaalde role namelijk `tab` of `tabpanel`. Als er geen direct children zijn kan hier voor `aria-owns` gebruikt worden om toch die parent-child relatie te leggen. Ik denk dat het hele ding misschien gewoon even gecheckt moet worden op correcte aria-labels. Ik zal daar nog even verder naar kijken

2024-07-31 12:13 UTC, CountNick commented
> Ha, fijn dat je hiermee bezig bent geweest. Ik heb nog wel wat vragen / opmerkingen, zoals je ziet in de comments. Je begeleidend schrijven bij de PR was wel wat summier. Dus heb zelf een Lighthouse check uitgevoerd bij een willekeurig project (Melkweg) om te zien welke issues je nu weg aan het werken bent.
> 
> Ik denk dat nog niet alles klopt. Is er een manier waarop jij dit in de browser test?
> 
> Lighthouse kan soms wat lastig te interpreteren zijn. Lighthouse maakt gebruik van de "axe-core". Er is ook een eigen Axe Devtools, die ik wel eens gebruik. Die geeft soms net wat meer uitleg. ([Chrome extension](https://chromewebstore.google.com/detail/axe-devtools-web-accessib/lhdoppojpmngadmnindnejefpokejbdd))
> 
> Daarnaast geeft Lighthouse ook nog wat "best practices". Het lijkt me goed om die ook mee te nemen. In dit geval gaat het vooral om een CSS aanpassing, dus die is relatief eenvoudig.
> 
> Best practices zijn in dit geval non-normatief, wat zoveel betekent als dat ze niet verplicht zijn volgens de guidelines. Maar wel goed om even mee te pakken indien mogelijk. <img alt="Screenshot 2024-07-30 at 15 09 08" width="745" src="https://private-user-images.githubusercontent.com/13998672/353469554-48206a39-5045-4671-a9a1-e29eb3561209.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MjgxNzksIm5iZiI6MTcyMjQyNzg3OSwicGF0aCI6Ii8xMzk5ODY3Mi8zNTM0Njk1NTQtNDgyMDZhMzktNTA0NS00NjcxLWE5YTEtZTI5ZWIzNTYxMjA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDEyMTExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3MDliY2I2ZDQwYmUyYTdkNmNlN2QxYjU4NmM4ZDRkNDkyMmNhNTBiZmUzNDQ0YmFlNTA3MjMwODc4NzQxYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uzBG-mwSwFOB3rLKQ64Tqty4bid8wdb3AAS3sbyhqsA">

Ik test dit nu door lokaal een npm link op te zetten voor de package. Zo kan ik lokaal changes maken en snel weer een lighthouse test draaien. Excuus, ik ben inderdaad vergeten de exacte errors te beschrijven.

2024-07-31 13:19 UTC, CountNick commented on src/dialog-tablist.mjs
> +            aria-owns="${PREFIX}__tab-list"
Afgaande op wat er op MDN staat denk ik toch niet dat deze `role="tab"` hier onterecht op staat: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tab_role. Hier staat namelijk het volgende `The ARIA tab role indicates an interactive element inside a tablist that, when activated, displays its associated tabpanel.` Op zich is dit ook wel het interactieve element in de tablist die er voor zorgt dat de `tabpanel` word getoond

2024-08-01 13:59 UTC, MicheleNL requested changes
Ik denk dat de originele implementatie het nu wat moeilijk maakt, ik heb bijgevoegd hoe de tabs-implementatie er idealiter uitziet. Laat vooral weten als we hier samen even moeten induiken.

2024-08-01 13:59 UTC, MicheleNL commented on src/dialog-tablist.mjs
> +      <li part="${PREFIX}__tab-list-item" role="tab">
Eigenlijk dient de `role='tab'` maar op 1 niveau te worden toegevoegd. Nu heb je semantisch gezien een tab in een tab. (Als je hem niet op 1 van de 2 plekken verwijdert). 

Ik denk dat de originele tabs-opzet binnen deze package eigenlijk niet ideaal is. Normaliter is de tablist hetgeen wat de tabjes representeert. En onder de tablist heb je dan verschillende tabpanelen. 
Hier zitten de tabpanelen genest in de tablist. 

Zie ook:

![image](https://github.com/user-attachments/assets/5992aecb-f381-444d-91ee-d39bdd91de19)

En op deze pagina zie je een standaard implementatie die eigenlijk gevolgd zou moeten worden:

https://www.w3.org/WAI/ARIA/apg/patterns/tabs/examples/tabs-manual/#tablist-1

Overigens ben ik niet getrouwd met het idee dat dit perse een tablist moet blijven, het kan waarschijnlijk ook versimpeld worden naar een lijst zoals je vaak ziet bij FAQ-items.

2024-08-29 07:18 UTC, MicheleNL commented on src/dialog-tablist.mjs
> +      <li part="${PREFIX}__tab-list-item" role="tab">
@CountNick Wat betekent dit effectief? Is het wat jou betreft dan bij deze afgerond en is deze PR dan weer ready for review? Laat me weten als ik weer moet kijken :)

2024-09-11 12:56 UTC, MicheleNL requested changes
Volgens mij vind ik dit niet goed, ik heb dit lokaal bekeken en ik lijk nu te zien dat een element met de rol `tabpanel` genest is in een element met de rol `tab`. Dat is niet de bedoeling. 

Het is in principe okay om pragmatisch te werk te gaan, maar ik ben er ook geen fan van om wijzigingen te doen om Lighthouse maar tevreden te stellen. Al zouden we het daarvoor doen, dan denk ik dat we hier niet zoveel mee opschieten, want Lighthouse lijkt nu ook nog steeds toegankelijkheidsfouten te rapporteren.

Mocht ik dit verkeerd hebben gezien, laat het me vooral weten. Als dit te maken heeft met beschikbare tijd, dan zou ik liever zien dat we dit op een tijdstip oppakken wanneer we met een gedegen oplossing kunnen komen. 

<img width="778" alt="Screenshot 2024-09-11 at 14 53 05" src="https://github.com/user-attachments/assets/b323a197-6a3b-4d06-9309-bd6025239606">

2026-06-19 06:55 UTC, harmenjanssen commented
Het is wel mooi geweest met deze PR!

2026-06-19 06:55 UTC, closed without merging